sudo: false
language: node_js
cache: npm
node_js:
  - "8.3"
notifications:
  email: false
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
